buildingSMART/validate

- backend/apps/ifc_validation/checks/check_gherkin.py
- backend/apps/ifc_validation_bff/views_legacy.py
- frontend/src/DashboardTable.js
- frontend/src/Report.js
- frontend/src/index.js
- `GHERKIN_REPO_DIR` appears to be set nowhere
- `os.EX_SOFTWARE` does not exist on win
- dashboard sort order
- split reports
> Some UI and integration attempts

- backend/apps/ifc_validation/views.py
- backend/apps/ifc_validation_bff/views_legacy.py
- backend/core/settings.py
Quick fix: apply same max. as in UI; in vNEXT we will make this a bit more realistic and configurable + some better UX
See [VAL-327](https://bsi-technicalservices.atlassian.net/browse/VAL-327)
> quick fix for v0.6 - max number of files set to 100 to align with UI

- frontend/src/DashboardTable.js
See VAL-347 - check https://dev.validate.buildingsmart.org to confirm
> Changed the tooltip text

- backend/apps/ifc_validation/templates/validation_completed_email.html
- frontend/src/BsddTreeView.js
- frontend/src/DashboardTable.js
- frontend/src/GherkinResult.js
- frontend/src/Report.js
- frontend/src/SchemaResult.js
- frontend/src/SyntaxResult.js
Changes as per VAL-346
See https://dev.validate.buildingsmart.org to confirm
> Consistent naming of checking parts

- backend/apps/ifc_validation/tasks.py
Include Model in get_or_create() - unique key = stepfile_id, ifc_type and model
> Include Model in get_or_create()

- backend/apps/ifc_validation/tasks.py
Note:
- @rw-bsi please suggest how to tie this into the celery workflow, I didn't really understand chord() this is probably not how we want it
- couldn't really test because the checked in report view doesn't show instances yet
> instance_completion_substask

- backend/apps/ifc_validation/tasks.py
- backend/apps/ifc_validation_bff/views_legacy.py
- frontend/src/DashboardTable.js
- frontend/src/Report.js
- frontend/src/SchemaResult.js
- (please ignore the first two commits, they are part of a separate PR)
- update legacy view:
- combine: status_schema+status_prereq serverside
- combine: status_ia + status_ip serverside
- separate out  outcomes over:  gherkin_rules_validation_task, prerequisites_validation_task, industry_practices_validation_task
- update frontend:
- minimal update to schema report rendering to accept also a gherkin outcome (minimal because all of this should be unified anyway)
- concatenate schema_result + prerequisites_validation_task.results client-side
> Critical prerequisites

- .gitignore
- backend/Makefile
- backend/requirements.txt
- docker/backend/Dockerfile
> fix to use specific version of icopenshell

- docker/backend/Dockerfile
- frontend/src/GherkinResult2.js
- add dependencies `wget` and `unzip` for ifcopenshell install in docker
- fix bug for expected / observed values in UI
> minor fixes before redploying

- backend/apps/ifc_validation/tasks.py
- backend/apps/ifc_validation/tests_tasks.py
default to utc tz (to get rid of warnings)
> default to utc tz

- frontend/src/Dz.js
- added file size limit (configurable, default 256 MB)
- initial snackbar/toast notification support
> File size limit + snackbar support

- frontend/src/GeneralTable.js
> Hide 'License' field

- backend/apps/ifc_validation_bff/views_legacy.py
- frontend/src/GherkinResult2.js
- frontend/src/SchemaResult.js
- frontend/src/SyntaxResult.js
- fixed paging + grouping
- fixed overall + individual row colors (based on severity)
- added checkbox to Schema report
- increased consistency of margin/padding
> fix paging, colors and consistency

- backend/apps/ifc_validation_bff/views_legacy.py
> fix for failed validations floating on top

- backend/apps/ifc_validation/admin.py
- backend/apps/ifc_validation/email_tasks.py
- backend/apps/ifc_validation/serializers.py
- backend/apps/ifc_validation/urls.py
- backend/apps/ifc_validation_bff/urls.py
- backend/apps/ifc_validation_bff/views_legacy.py
Depends on https://github.com/buildingSMART/ifc-validation-data-model/pull/13/files
URLs would look something like `http://localhost:3000/report_file/r368253674` now.
> Coprime id obfuscation

- backend/core/email_tasks.py
- backend/core/templates/user_registered_admin_email.html
- backend/core/views_auth.py
Exclude part of the message that asks to activate the user account if the user account is already active (internal email)
> Exclude activation message

- backend/apps/ifc_validation/admin.py
- backend/apps/ifc_validation/templates/admin/hard_delete_intermediate.html
- backend/apps/ifc_validation/views.py
- backend/apps/ifc_validation_bff/views_legacy.py
- backend/core/settings.py
- backend/requirements.txt
- frontend/src/Report.js
- implement soft_delete
- implement hard_delete (in Django Admin only)
- add intermediate confirmation page
- show 404-NotFound when request does not exist (or is deleted)
- hide 'Add' buttons for Validation Request etc...
> implement soft_delete and 404 for non-existing report

- backend/apps/ifc_validation/tasks.py
- fixed chord error handler invocation
- fixed instance completion task triggering even on failure
- workaround for schema validation error not triggering b/c Parse Info failure (a bit of a hack, I know)
> Fix issue due to workflow error

- backend/apps/ifc_validation/tasks.py
Fix for processing of non-IFC files (VAL-443) - uploading a non-IFC file
Pre:
Post:
> Improve error handling in STEP Syntax Task

- docker/frontend/nginx/default.conf
Downloading of uploaded files within Django Admin
> (low prio) Update default.conf - file download within Django Admin

- frontend/src/GherkinResult.js
Display optional context for One of fields. See https://github.com/buildingSMART/ifc-gherkin-rules/pull/185
> One of context

- backend/apps/ifc_validation/checks/check_bsdd.py
VAL-468 - bSDD task failures - parse bit more defensive
> VAL-468 - bSDD task failures

- backend/apps/ifc_validation/checks/check_bsdd.py
Don't parse IfcEntities / bSDD when N/A
> VAL-476 - Optimize bSDD Validation Task

- frontend/src/SchemaResult.js
> IVS-23-Add description to critical error message

- .gitignore
- check-submodules.sh
- redeploy.sh
- added letsencrypt to .gitignore
- added utility scripts
> IVS-47 sync deployed changes

- backend/apps/ifc_validation/admin.py
Derived from Django Admin UserAdmin class - shows a default Change Password link on the User form
> Update UserAdmin class

- backend/apps/ifc_validation_bff/views_legacy.py
USE_WHITELIST for local development
> USE_WHITELIST for local development

- backend/core/settings.py
Merge `main` into `development`
> IVS_29 Sync main into development

- backend/apps/ifc_validation/tasks.py
> Fix issue with schema validation

- backend/Makefile
- docker/backend/Dockerfile
Updated ifcopenshell version to v0.8.0
> Align ifcopenshell versions

- README.md
- backend/apps/ifc_validation/tasks.py
- backend/apps/ifc_validation_bff/views_legacy.py
- frontend/src/App.js
- frontend/src/DashboardTable.js
- disabled running bSDD checks
- bSDD report hidden (returns 404)
- bSDD column hidden
> Disabled bSDD checks + rendering

- .gitignore
- check-submodules.sh
- redeploy.sh
- update helper scripts
- update .gitignore
> IVS-29 update build deploy pipeline

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/Dashboard.js
- frontend/src/FeedbackWidget.js
- frontend/src/Report.js
Embedded Typeform to collect end-user feedback
(only available on App, Dashboard and Report)
> IVS-103 Embed feedback form

- frontend/src/DashboardTable.js
Moved delete toolbar button to the far left
> IVS-107 feedback widget overlaps with delete icon

- docs/ref/index.md
- docs/ref/normative-rules/ALB021.md
> rename ALA001 to ALB021 in docs

- frontend/src/GherkinResult.js
> add additional information for alignment continuity reporting

- frontend/src/GherkinResult.js
IVS-133
We should probably structure the presentation layer a bit better.
Together with https://github.com/buildingSMART/ifc-gherkin-rules/pull/303
> PJS003 - Improve error message

- frontend/src/GherkinResult.js
- frontend/src/SchemaResult.js
Displays number of outcomes to Gherkin and Schema reports
Example:
> IVS-204 - display number of outcomes

- backend/apps/ifc_validation/tasks.py
Waiting for new ifopsh build still for this to work
> Mark success when validate statuscode < 0

- backend/apps/ifc_validation/tasks.py
Same as https://github.com/buildingSMART/validate/pull/119 but with development as base
> tfk-validate-return-code - merge to dev

- frontend/src/GherkinResult.js
- frontend/src/SchemaResult.js
> IVS-205 - Only display title suffix for warnings & errors

- backend/apps/ifc_validation/admin.py
- added Authoring Tool
- added Is Vendor ?
- updated searching/filtering/ordering
Preview:
> IVS-311 - Update Django Admin for ValidationRequest model

- docker/frontend/docker-entrypoint.d/99-configure-letsencrypt.sh
add `--hsts` option to certbot
> IVS-364 - Add header for HSTS

- frontend/src/GherkinResult.js
Quick band-aid to clean things back up.
> fix formatting of 'Observed' field in gherkin results

- backend/apps/ifc_validation/admin.py
Implemented via an annotation (can't sort on `@property` ...)
> IVS-398 - Ability to sort ValidationRequest & ValidationTask in Django Admin

- backend/apps/ifc_validation/admin.py
To quickly gauge importance and have a sorting capability
Example:
> IVS-402 - Display number of Requests per User

- backend/apps/ifc_validation/admin.py
Surface two extra fields in Django Admin
> IVS-405 / IVS-414 - Capture email pattern and legal name

- backend/apps/ifc_validation/admin.py
Ability to navigate or filter via clickable columns
> IVS-409 - small Django Admin improvements

- backend/apps/ifc_validation/tasks.py
- Add link authoring tool to company entry 
- Update existing authoring tool if no company was previously linked
> IVS-412 - Link AuthoringTool to Company

- backend/apps/ifc_validation/tasks.py
- frontend/src/DashboardTable.js
+ green info button when passing the header validation
> IVS-425 - Unified authoring tool evaluation

- backend/apps/ifc_validation/admin.py
- removal of obsolete columns (nbr of elements etc...)
- display file name as specified in header
- add column to navigate from ValidationRequest to Model
- enable sorting on 'Deleted?' column
- rearrange columns and column names
> IVS-427 - Django Admin improvements

- backend/apps/ifc_validation/admin.py
- backend/apps/ifc_validation/templates/admin/assign_company_intermediate.html
Per the title. Note: this is the manual assignment based on email address pattern, in Django Admin.
Plan is to run it automatically during user registration (see [IVS-413](https://buildingsmart.atlassian.net/browse/IVS-413))
See preview of screen flow in Jira ticket:
https://buildingsmart.atlassian.net/browse/IVS-417
[IVS-413]: https://buildingsmart.atlassian.net/browse/IVS-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IVS-417 - Manually link users to selected Companies based on email pattern(s)

- .github/workflows/ci_cd.yml
- backend/Makefile
- backend/apps/ifc_validation/fixtures/pass_header_policy.ifc
- backend/apps/ifc_validation/fixtures/valid_file_with_tz.ifc
- backend/apps/ifc_validation/test_settings.py
- backend/apps/ifc_validation/tests/tests_bsdd_validation_task.py
- backend/apps/ifc_validation/tests/tests_parse_info_task.py
- backend/apps/ifc_validation/tests/tests_schema_validation_task.py
- backend/apps/ifc_validation/tests/tests_syntax_validation_task.py
- fixed broken tests
- refactor tests
`make test` in `backend` folder should now run consistently
> IVS-384 - Increase and refactor test suite

- backend/apps/ifc_validation/admin.py
> IVS-440 - Assign based on email address not finding any eligible users fails (low prio)

- backend/apps/ifc_validation/tests/tests_parse_info_task.py
Approve PR in other repo first
https://github.com/buildingSMART/ifc-validation-data-model/pull/33
> IVS-442 - Additional unit tests (approve other PR first!)

- backend/apps/ifc_validation/admin.py
- backend/apps/ifc_validation_bff/views_legacy.py
Automatically assign users to company and mark as `is_vendor` if email address matches pattern
(+ update Django Admin implementation to use same detection logic)
> IVS-413 - Automatically assign users to company and mark as is_vendor

- frontend/src/GherkinResult.js
> handle reporting of 2D position for LIP002 (IVS-173)

- docker/backend/server-entrypoint.sh
- docker/backend/worker-entrypoint.sh
- Stop container if Django Migrations fail
- Add Django Migrations to Worker entrypoint
> IVS-244 - Halt if Django Migrations fail

- backend/apps/ifc_validation/admin.py
long overdue; I realize it's a workaround and not ideal - but shortest and safest way I found so far without triggering a full queryset evaluation
@aothms perhaps we can change `to_private_id` in `IdObfuscator` to fail or yield -1 if prefix doesn't match - we now ignore it with [1:]...
eg.
```
@classmethod
def to_public_id(cls, priv_id, override_cls=None):
return id_prefix_mapping[override_cls or cls] + str(priv_id * COPRIMESECRET % PRIMEMODULO)
@staticmethod
def to_private_id(pub_id):
return int(pub_id[1:]) * INVERSE_COPRIME % PRIMEMODULO
```
> IVS-38 - Workaround for searching for public_id

- backend/core/settings.py
- backend/core/urls.py
- backend/requirements.txt
- docker/frontend/nginx/default.conf.template
To quickly run SQL queries in Django Admin UI or /sqlexplorer (read-only!)
Helps with troubleshooting and/or running ad-hoc queries
> IVS-509 - Enable Django SQL Explorer

- docs/dev/gherkin_deep_dive.md
Including `@no-activation`
https://github.com/buildingSMART/ifc-gherkin-rules/pull/408
> IVS-552 - Include feature tags in documentation

- backend/apps/ifc_validation_bff/views_legacy.py
Existing reports pre-signature feature fail to render
> IVS-559 - Existing reports pre-signature feature fail to render

- backend/apps/ifc_validation/chart_views.py
> IVS-581 - Consistent timescaling

- backend/apps/ifc_validation_bff/views_legacy.py
> IVS-579 - Failed to post back client side errors

- .github/workflows/ci_cd.yml
- Makefile
- README.md
- backend/Makefile
- docker/backend/Dockerfile
As added in `main` https://github.com/buildingSMART/validate/commit/085944b1c1beb02432bee17f8f8d3dbcf087ac3b#diff-5024268fbb0b80c2fca407bd63672f2e0e8c2b61e87f3bdd361e6a7a41a9dda3
> IVS-106 - Update local deployment instructions

- backend/apps/ifc_validation/admin.py
- backend/apps/ifc_validation/filters.py
- backend/core/filters.py
- backend/core/templates/admin/advanced_input_filter.html
- e2e/tests/django_admin.test.js
- advanced filter for `Produced By`
- advanced filter for `Created By`
- updated Django Admin e2e tests
> IVS-611 - Update Django Admin filters

- backend/apps/ifc_validation/admin.py
marked 'Is Vendor' columns as boolean in User screen
> IVS-625 - Update Django Admin (low-prio)
