buildingSMART/validate

- frontend/src/DashboardTable.js
Disables revalidation option in dashboard UI - see VAL-307
(admin + backend code is still available, but can now only be invoked via Django admin)
> disabled revalidate option in dashboard UI

- docker-compose.infra_only.yml
map Postgres DB port in infra_only Docker compose file (re. discussion with Scott earlier this week)
> map Postgres DB port in infra_only Docker compose file

- backend/apps/ifc_validation/email_tasks.py
- backend/apps/ifc_validation/templates/validation_completed_email.html
only include valid/invalid/warning report sections (now mirrors the status of the dashboard)
> only include valid/invalid/warning report sections in completion email

- frontend/src/Dz.js
> Update text of file size limit toast message

- backend/core/settings.py
- backend/core/views_auth.py
Kept whitelisting of users (aka creating user accounts but setting is_active to False) for non-PRODUCTION environments
> disable whitelist in PRODUCTION

- backend/apps/ifc_validation/admin.py
Django Admin does not support searching on calculated/derived properties - `public_id` is implemented as a `@property`
```
@property
def public_id(self):
return self.to_public_id(self.id)
...
```
Future change might be to calculated this value and persist the `public_id` field in the DB
> Fix for VAL-426 - disable search on 'public_id'

- backend/apps/ifc_validation/admin.py
Allow sorting on FileSize field in Django Admin - one-line fix
> VAL-340 - Allow sorting on FileSize field in Django Admin

- backend/apps/ifc_validation/email_tasks.py
- backend/apps/ifc_validation/templates/validation_ack_admin_email.html
- backend/apps/ifc_validation/templates/validation_reval_admin_email.html
Simple fix - replace 
[email] ([email]) - eg. john@doe.net (john@doe.net)
with 
[user full name] ([email] - eg. John Doe (john@doe.net)
> VAL-409 - Replace redundant email with user full name

- backend/apps/ifc_validation_bff/views_legacy.py
With the adjusted line the parsing will include 'Scenario Outline:'
Handling `SPS007` parsing 
So then only the following line would be displayed as the description: 
`The rule verifies that spatial containment via IfcRelContainedInSpatialStructure is utilised in accordance with Contept Template for Spatial Containment`
> End feature description parsing at 'Scenario Outline:'

- backend/apps/ifc_validation_bff/views_legacy.py
Clearer message by also including the expected column in case errors due to the `@critical `tag.
In the case of IFC101, this would be
`{"oneOf": ["IFC4X3_ADD2", "IFC4", "IFC2X3"]} `
Alternatively, we can come up with something nicer for displaying these kind of messages, such as:
- Displaying the rule in the `normative rules` column as the only error. 
- Custom messaging for rules with a `critical` tag. For instance, include the feature description.
> IVS-13 clearer message for critical error

- frontend/src/SchemaResult.js
New output 
Schema rendering for 'actual schema errors' (not coming from gherkin) remains the same. For instance;
cc @evandroAlfieri
> IVS-23 Critical error message in schema column

- backend/core/settings.py
As per [the comment on the previous PR](https://github.com/buildingSMART/validate/pull/84#discussion_r1690612156)
> `eval` cannot operate on boolean values so the default to get() needs to be a string as well. Also `eval` is probably not very safe, better use `ast.literal_eval()`
See also the[ dangers of ast](http://nedbatchelder.com/blog/201206/eval_really_is_dangerous.html)
> Use ast.literal_eval rather than eval()

- frontend/src/GherkinResult.js
Provides formatting for proper display of expected and calculated values for alignment continuity. See buildingSMART/ifc-gherkin-rules#243
> add formatting for displaying results of alignment continuity formatting

- frontend/src/GherkinResult.js
- frontend/src/mappings.js
Take into account severity when folding duplicate outcomes.
> IVS-117 outcome massaging

- frontend/src/GherkinResult.js
This is required for vertical and cant alignment continuity reporting.
Before:
After:
> replace 'Tangent Direction' with 'Gradient'

- backend/Makefile
for the mac aficionados: added `install-macos` target (pulls in correct python package and uses correct unzip format)
```
install-macos: venv
. $(VIRTUAL_ENV)/bin/activate && \
pip install --upgrade pip && \
pip install -r requirements.txt && \
wget -O /tmp/ifcopenshell_python.zip "https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-311-v0.7.9-c18e4ea-macos64.zip" && \
mkdir -p $(VIRTUAL_ENV)/lib/python3.11/site-packages && \
unzip /tmp/ifcopenshell_python.zip -d .dev/venv/lib/python3.11/site-packages && \
rm /tmp/ifcopenshell_python.zip
```
> Update Makefile to include macos specific target

- frontend/src/GherkinResult.js
Suppress display of information about tangent direction or gradient when the warning is being triggered by a deviation in position.
> clean up alignment continuity reporting

- backend/apps/ifc_validation_bff/views_legacy.py
- backend/core/settings.py
- frontend/src/GherkinResult.js
- frontend/src/Report.js
- frontend/src/SchemaResult.js
Limit # of outcomes to 10 (configurable) + moved some of grouping/title logic to backend
Example:
> IVS-205 - Limit number of outcomes per rule

- backend/apps/ifc_validation/admin.py
Ability to manage Version and UserAdditionalInfo in Django Admin
**IMPORTANT**: requires approval of PR in Data Model repo: https://github.com/buildingSMART/ifc-validation-data-model/pull/26
> IVS-239 - Version and UserAdditionalinfo

- .github/workflows/ci_cd.yml
- backend/Makefile
- backend/apps/ifc_validation/tasks.py
- docker/backend/Dockerfile
Should we delete submodule dependency @rw-bsi  ?
> IVS-255 - Run SPF as module & update ifcopenshell

- backend/apps/ifc_validation/admin.py
- backend/apps/ifc_validation/tasks.py
- only fetch/update `ModelInstance` records that require updating - for some reason `.bulk_update()` fails...
- promote `Instance_completion_subtask` into proper `ValidationTask` (to be able to track in UI)
- update `ModelInstance` admin screen
> IVS-235 - update Instance Completion task + update admin

- backend/apps/ifc_validation/serializers.py
- backend/apps/ifc_validation/views.py
- backend/core/settings.py
- do not require r/o fields in POST
- update authn/authz config
- fetch individual items by `public_id` instead of `id`
- support filtering by certain `public_id`(s)
> Fix for DRF API access

- backend/apps/ifc_validation/tasks.py
Before:
After:
(similar strategy as Gherkin Rules - aka temporarily store `stepfile-id`)
> IVS-314 - Incorrect instance links in schema validation

- .github/workflows/ci_cd.yml
- backend/Makefile
- docker/backend/Dockerfile
This is necessary for the correct processing of alignment data in models with non-SI units where IfcCurveSegment.ParentCurve is of type IfcPolynomialCurve.
(IVS-282)
> upgrade ifcopenshell version for polynomial coefficients fix

- .github/workflows/ci_cd.yml
- .gitmodules
- README.md
- backend/Makefile
- backend/README.md
- backend/apps/ifc_validation/admin.py
- backend/apps/ifc_validation/checks/check_gherkin.py
- backend/apps/ifc_validation/serializers.py
- backend/apps/ifc_validation/tasks.py
- backend/apps/ifc_validation/views.py
- backend/core/settings.py
- backend/requirements.txt
- docker/backend/Dockerfile
~Doesn't fully work yet. Seems that whitespace within strings is discarded. So MVD and authoring are wrong.~
> IVS-228 purepythonparser for critical gherkin checks and info extraction

- backend/apps/ifc_validation/admin.py
- backend/core/filters.py
- backend/core/utils.py
- Workaround for slow Postgres COUNT(*) - count distinct id's
- Additional date options for eg. `created` and `updated` fields
- Various smaller Django Admin improvements
> IVS-206 - Implement custom paginator and date filter

- backend/apps/ifc_validation/admin.py
Quickly gauge importance of a certain tool.
Example screenshot - Django Admin:
> IVS-407 - Display number of requests per Authoring Tool in Django Admin

- backend/apps/ifc_validation/email_tasks.py
- backend/apps/ifc_validation/templates/validation_ack_admin_email.html
- backend/apps/ifc_validation/templates/validation_reval_admin_email.html
- backend/core/email_tasks.py
- backend/core/settings.py
- backend/core/templates/user_registered_admin_email.html
Not impacting end users, only admin emails will have the name of the environment included in the body of the email
> IVS-395 - Include environment in admin emails (low prio)

- backend/apps/ifc_validation/tasks.py
Do not send upload confirmations to end users, only results/failures; all other email behaviour remains
> IVS-37 - Disable initial emails for end users

- backend/apps/ifc_validation_bff/views_legacy.py
- backend/core/settings.py
Because of the gherkin repo refactoring, the url for fetching description information was not correct anymore. 
I'm also dynamically pointing to the `development` or `main` branches. The downside to this is that the url will be incorrect as long as we haven't merged the future release/0.7.1 branch back into main. Is it worth the effort to point to the relevant release branch instead of main to avoid this?
> IVS-429 - Fetch correct description (url)

- docker/backend/server-entrypoint.sh
- docker/backend/worker-entrypoint.sh
replaced `nc` with `pg_isready`
more reliable as `pg_isready` checks more than just the network connectivity
https://www.postgresql.org/docs/current/app-pg-isready.html
> IVS-488 - FIX: Postgres DB isn't really ready

- backend/core/settings.py
Correctly parse DEBUG environment variable - will not render stacktrace etc
(we also used `ast.literal_eval` with USE_WHITELIST)
https://docs.djangoproject.com/en/dev/ref/settings/#debug
> IVS-504 - Fix DEBUG mode

- backend/Makefile
- backend/core/urls.py
replaced `static()` with own `re_path` implementation
Note: Django's static() doesn't work when `DEBUG = False`
> IVS-514 - Unable to download files in Django Admin when DEBUG = False

- backend/apps/ifc_validation/serializers.py
- backend/apps/ifc_validation/urls.py
- backend/apps/ifc_validation/views.py
Before: only `ValidationRequest`, `ValidationTask` and `ValidationOutcome` were accessible via the API
Now: `Model` is also available
> IVS-529 - Expose Model via API

- backend/Makefile
Replaces all shell-based virtual environment activations (`. venv/bin/activate && ...`) with direct calls to the virtual environment’s Python binary (`venv/bin/python`). This ensures consistent environment usage across Makefile targets such as `start-backend`, `start-worker*`, and test tasks, and prevents accidental fallback to global or incorrect venvs.
Also fixes inconsistent behavior when running background tasks like Celery workers, which locally pulled in a wrong Python interpreter from another path.
> IVS-532 - Use virtual environment Python binary directly in Makefile

- backend/apps/ifc_validation/views.py
- backend/core/settings.py
Current configuration:
- allowed to **submit 10 Validation Requests** per hour via the API
- allowed to **list/retrieve info via the API at a rate of 1000/hour** (or 100/hour if anonymous, which we don't allow)
```
'DEFAULT_THROTTLE_RATES': {
'anon': '100/hour',
'user': '1000/hour',
'submit_validation_request': '10/hour'
}
```
> IVS-492 - API Rate Limiting

- Makefile
- e2e/.gitignore
- e2e/package-lock.json
- e2e/package.json
- e2e/playwright.config.js
- e2e/tests/django_admin.test.js
- e2e/tests/global-setup.js
- e2e/tests/global-teardown.js
- e2e/tests/validate.test.js
- Playwright scaffolding
- 2 example test scenarios (one Django Admin, one Validate UI)
Run locally with `make e2e-test`
> IVS-31 - Added Playwright tests

- backend/apps/ifc_validation_bff/views_legacy.py
- e2e/tests/validate.test.js
Impacts new users or users who have cleared their cookies
(added Playwright tests that were failing before the fix)
> IVS-593 - Users are unable to self report vendor association

- backend/apps/ifc_validation/views.py
- backend/core/settings.py
- e2e/fixtures/valid_file.ifc
- e2e/tests/validate_api.test.js
- enforce file size limit of 256 MB when using the API
- added Playwright tests (positive/negative case)
> IVS-587 - Enforce file size limit via API

- backend/apps/ifc_validation/views.py
- backend/core/settings.py
- e2e/fixtures/invalid_file_extension
- e2e/fixtures/valid_file2.ifc
- e2e/tests/validate_api.test.js
Protects against and tests for common invalid scenarios:
- empty filename
- empty file (0 bytes)
- filename not ending with `'.ifc'`
- multiple files in one request
- missing authorization header
> IVS-604 - Reject invalid API usage

- backend/core/settings.py
- backend/core/urls.py
- e2e/tests/validate_api.test.js
- redirect /api to /api/swagger-ui (browsers)
- redirect /api to /api/schema (non-browsers)
- link to API quick-start documentation
- e2e tests
> IVS-623 - Redirect browsers hitting /api to Swagger UI

- backend/apps/ifc_validation/serializers.py
- e2e/tests/validate_api.test.js
Hide `model_id` and other fields in `ValidationRequest` JSON + e2e test
> IVS-641 - Hide internal db identifier fields

- backend/apps/ifc_validation/views.py
- e2e/tests/validate_api.test.js
> API Pagination - Bugfixes
